import { readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { marked } from 'marked';

const root = dirname(fileURLToPath(import.meta.url));
const source = readFileSync(join(root, 'old/content/homeindex.md'), 'utf8');
const tamil = readFileSync(join(root, 'old/content/index-Tamil.md'), 'utf8');
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
const arrow = icon('arrow-up-right');
const link = (url, text, style = 'text-link') => `<a class="${style}" href="${url}">${text}${arrow}</a>`;
const nav = [['index.html', 'Overview'], ['biography.html', 'The journey'], ['missions.html', 'Missions'], ['honours.html', 'Honours'], ['gallery.html', 'In focus']];
const page = (file, title, content, language = 'en') => {
  const tamilPage = language === 'ta';
  const html = `<!doctype html>
<html lang="${language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#161817"><meta name="description" content="Dr. Mylswamy Annadurai, the Moon Man of India. Explore his life, ISRO missions, honours and legacy in science and education."><title>${title} | Dr. Mylswamy Annadurai</title><link rel="stylesheet" href="assets/site.css"><script defer src="assets/lucide.js"></script><script defer src="assets/site.js"></script></head>
<body class="${file === 'index.html' ? 'home' : 'interior'}"><a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><a class="identity" href="index.html" aria-label="Dr. Mylswamy Annadurai home"><span class="identity-mark">ma<span>.</span></span><span class="identity-name">DR. MYLSWAMY<br>ANNADURAI</span></a><nav id="navigation" aria-label="Main navigation">${nav.map(([url, label]) => `<a href="${url}" ${file === url ? 'aria-current="page"' : ''}>${label}</a>`).join('')}</nav><div class="header-actions"><a class="language" href="${tamilPage ? 'index.html' : 'tamil.html'}" lang="${tamilPage ? 'en' : 'ta'}">${tamilPage ? 'English' : 'தமிழ்'}</a><button class="icon-button menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="navigation">${icon('menu')}</button></div></header>
<main id="main">${content}</main>
<footer><div class="footer-top"><div><span class="eyebrow">SCIENCE. SERVICE. POSSIBILITY.</span><h2>A life looking forward.</h2></div>${link('biography.html#beyond', 'Beyond ISRO')}</div><div class="footer-bottom"><a href="index.html">Dr. Mylswamy Annadurai</a><span>From Kodhawady. For the world.</span><a href="sources.html">Sources &amp; image credits</a><a href="#top" class="back-top" aria-label="Back to top">${icon('arrow-up')}</a></div></footer></body></html>`;
  writeFileSync(join(root, file), html);
};
const heading = (number, title, description) => `<section class="page-heading wrap"><span class="eyebrow">${number} / THE MOON MAN OF INDIA</span><h1>${title}</h1><p>${description}</p></section>`;
const chapter = (number, title, content) => `<section class="chapter wrap"><div class="chapter-label"><span class="eyebrow">${number}</span><h2>${title}</h2></div><div class="chapter-body">${content}</div></section>`;
const missionCards = `<div class="mission-grid"><a class="mission-card lunar" href="missions.html#chandrayaan-1"><span class="eyebrow">01 / LUNAR EXPLORATION</span><img src="assets/moon.jpg" alt="The near side of the Moon" loading="lazy"><div><span class="mini">PROJECT DIRECTOR · 2004–2009</span><h3>Chandrayaan-1 ${arrow}</h3><p>India's first journey to the Moon.</p></div></a><a class="mission-card earth" href="missions.html#satellites"><span class="eyebrow">02 / CONNECTING INDIA</span><img src="assets/earth.jpg" alt="Earth photographed from space" loading="lazy"><div><span class="mini">OPERATIONS &amp; MISSION LEADERSHIP</span><h3>A nation, connected ${arrow}</h3><p>From INSAT to India's student satellites.</p></div></a></div>`;

page('index.html', 'The Moon Man of India', `<section class="hero" id="top"><img class="hero-portrait" src="assets/portrait.jpg" alt="Dr. Mylswamy Annadurai, Indian aerospace engineer" fetchpriority="high"><div class="hero-shade"></div><div class="hero-content"><div class="eyebrow hero-kicker"><span class="status-dot"></span> THE MOON MAN OF INDIA</div><h1><span>Dr. Mylswamy</span><br>Annadurai<span class="red">.</span></h1><p>A village in Tamil Nadu. A vision beyond Earth.<br>A life dedicated to taking India further.</p>${link('biography.html', 'Discover the journey', 'button primary')}<div class="hero-honour">${icon('award')}<span>PADMA SHRI<br><strong>Science &amp; Engineering · 2016</strong></span></div></div><div class="hero-bottom"><span>ENGINEER. EXPLORER. EDUCATOR.</span><a href="#introduction">A life in perspective ${icon('arrow-down')}</a><span>01 — 06</span></div></section>
<section class="intro wrap" id="introduction"><div><span class="eyebrow">01 / THE PERSON BEHIND THE MISSIONS</span><h2>Grounded in his roots.<br><em>Boundless in his vision.</em></h2></div><div><p>Born in Kodhawady, educated in Coimbatore, and shaped by 36 years at ISRO. Dr. Mylswamy Annadurai helped turn a nation's ambition into journeys beyond Earth.</p><p>Project director of Chandrayaan-1. Former director of the ISRO Satellite Centre. Today, an advisor to innovators and a voice for science and education.</p>${link('biography.html', 'Meet Dr. Annadurai')}</div></section>
<div class="stats wrap"><div><strong>36<span>years</span></strong><p>At the Indian Space Research Organisation</p></div><div><strong>1982<span>– 2018</span></strong><p>From engineer to centre director</p></div><div><strong>2016</strong><p>Padma Shri, Government of India</p></div></div>
<section class="mission-section wrap"><div class="section-top"><div><span class="eyebrow">02 / A NATION REACHES FURTHER</span><h2>Missions that matter.</h2></div>${link('missions.html', 'Explore the missions')}</div>${missionCards}</section>
<section class="journey-preview"><div class="wrap"><div class="section-top"><div><span class="eyebrow">03 / THE MAKING OF A SCIENTIST</span><h2>Small beginnings.<br>Extraordinary horizons.</h2></div>${link('biography.html#chronicle', 'The complete chronology')}</div><div class="milestones">${[['1958','Kodhawady, Tamil Nadu','Born on 2 July in a village near Pollachi.'],['1982','A new chapter at ISRO','Joined after his postgraduate studies at PSG.'],['2008','India looks to the Moon','Chandrayaan-1 launches on 22 October.'],['2015','Leading from the front','Appointed director of the ISRO Satellite Centre.']].map(([year,title,text]) => `<article><span class="year">${year}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></div></section>
<section class="legacy wrap"><span class="eyebrow">04 / THE NEXT GENERATION</span><h2>The next great journey<br>begins with <em>curiosity.</em></h2><div><p>His work continues beyond the space programme: guiding technology ventures, supporting education, and making science part of the public conversation.</p>${link('biography.html#beyond', 'Science beyond the launchpad')}</div></section>`);

const chronology = source.split('## Chronicle Profile')[1].split('## Gallery')[0];
const timelineTokens = marked.lexer(chronology).find(token => token.type === 'list');
const timeline = timelineTokens.items.map(item => {
  const first = item.text.split('\n')[0];
  const match = first.match(/\*\*(.*?)\*\*\s*—\s*(.*)/);
  return match ? `<article class="timeline-row" data-era="${Number(match[1].slice(0,4)) < 1982 ? 'education' : Number(match[1].slice(0,4)) < 2019 ? 'isro' : 'beyond'}"><span>${escape(match[1])}</span><h3>${escape(match[2])}</h3></article>` : '';
}).join('');
page('biography.html', 'The journey', `${heading('01', 'From a village.<br>To the Moon.', 'An engineer by training. An explorer by vocation. A life shaped by education, teamwork and service.')}<div class="biography-photo wrap"><img src="assets/portrait.jpg" alt="Portrait of Dr. Mylswamy Annadurai"><div><span class="eyebrow">DR. MYLSWAMY ANNADURAI</span><p>“Moon Man of India”</p><span>Born 2 July 1958 · Kodhawady, Tamil Nadu</span></div></div>${chapter('01 / ROOTS', 'An education<br>in possibility.', '<p>After his early education in his native village, Annadurai studied engineering at the Government College of Technology, Coimbatore, graduating in 1980. He earned his master\'s degree at PSG College of Technology in 1982 and obtained his PhD from Anna University.</p><p>That same year, 1982, he joined the Indian Space Research Organisation. Work on satellite simulation and spacecraft operations became the foundation for a career in mission leadership.</p>')}${chapter('02 / LEADERSHIP', 'Building missions.<br>Building teams.', '<p>His assignments stretched from the IRS and INSAT satellite programmes to EDUSAT and lunar exploration. As project director of Chandrayaan-1 (2004–2009), he led the team behind India\'s first lunar mission.</p><p>He served as project director of Chandrayaan-2 during its development from 2008 to 2013, and as programme director for Indian Remote Sensing and Small, Science and Student Satellites from 2011 to 2015. From 2015 to 2018, he directed the ISRO Satellite Centre, now the U R Rao Satellite Centre.</p>')}
<section class="timeline-section wrap" id="chronicle"><div class="section-top"><div><span class="eyebrow">03 / THE CHRONICLE</span><h2>A lifetime, in chapters.</h2></div><div class="filters" aria-label="Filter chronology"><button class="active" data-era-filter="all" aria-pressed="true">All years</button><button data-era-filter="education" aria-pressed="false">Education</button><button data-era-filter="isro" aria-pressed="false">ISRO</button><button data-era-filter="beyond" aria-pressed="false">Beyond ISRO</button></div></div>${timeline}</section>
<section id="beyond">${chapter('04 / STILL LOOKING FORWARD', 'Science in<br>everyday life.', '<p>After retiring from ISRO, Dr. Annadurai continued to advise startups, charities and institutions. His recorded appointments include vice president of the Tamil Nadu State Council for Science and Technology (2019–2023), and advisory work in Earth observation, biotechnology, aerospace and education.</p><p>The chronology above preserves appointments as listed in the September 2026 source snapshot; open-ended dates are the source\'s record, not independent confirmation of a current appointment.</p><h3>Writing in Tamil</h3><p>The original archive features <em>Kaiyaruke Nila</em> and <em>Sirakai Virikkum Mangalayan</em>, bringing space exploration into Tamil literary life. It also records the C. Pa. Aditanar Literary Award in 2013.</p>')}</section>`);

page('missions.html', 'Missions', `${heading('02', 'A nation’s ambition.<br>A shared endeavour.', 'Satellite operations, lunar exploration and the teams that made them possible.')}<section class="wrap">${missionCards}</section>${chapter('01 / 2004–2009', '<span id="chandrayaan-1">Chandrayaan-1</span>', '<span class="role-label">PROJECT DIRECTOR</span><p>India\'s first lunar mission launched on 22 October 2008 and entered lunar orbit on 8 November. Its scientific instruments brought together contributions from India and international partners.</p><p>Dr. Annadurai led the project during 2004–2009. The mission helped transform our understanding of the Moon, including evidence of water molecules on the lunar surface from NASA\'s Moon Mineralogy Mapper.</p><a class="text-link" href="https://www.isro.gov.in/Chandrayaan_1.html">Mission record at ISRO &#8599;</a>')}${chapter('02 / 2008–2013', 'Chandrayaan-2', '<span class="role-label">PROJECT DIRECTOR · DEVELOPMENT PHASE</span><p>Dr. Annadurai\'s recorded assignment covers the early development phase of Chandrayaan-2, from 2008 to 2013. This work contributed to the next chapter of India\'s lunar exploration programme.</p><p>His project-director tenure preceded the mission\'s 2019 launch. The chronology distinguishes that development role from the later launch and mission operations.</p>')}${chapter('03 / 2011–2015', 'A wider horizon.', '<span class="role-label">PROGRAMME DIRECTOR · IRS &amp; SSS</span><p>As programme director for Indian Remote Sensing and Small, Science and Student Satellites, his responsibilities encompassed a broad scientific portfolio, including the Mars Orbiter Mission.</p><p>Mangalyaan launched on 5 November 2013 and entered Mars orbit on 24 September 2014, a landmark in India\'s interplanetary exploration.</p><a class="text-link" href="https://www.isro.gov.in/MarsOrbiterMission.html">Mars Orbiter Mission at ISRO &#8599;</a>')}${chapter('04 / OPERATIONS & LEADERSHIP', '<span id="satellites">Space, in service<br>of Earth.</span>', '<p>Before the lunar missions came years of operating spacecraft. Annadurai served as spacecraft operations manager for IRS-1A and INSAT-2A, and mission director across the INSAT-2C, INSAT-2D, INSAT-2E, INSAT-3B, GSAT-1 and INSAT-3E programmes.</p><p>As associate project director of EDUSAT (2003–2005), he contributed to a mission dedicated to education. Later, as director of the satellite centre (2015–2018), he led work spanning communication, remote sensing, navigation and space science.</p>')}`);

const awardMarkdown = source.split('## Awards and achievements')[1].split('## Chronicle Profile')[0];
let awardCategory = '';
let awardIndex = 0;
const awards = [];
for (const token of marked.lexer(awardMarkdown)) {
  if (token.type === 'heading') awardCategory = token.text;
  if (token.type === 'list') for (const item of token.items) awards.push({ category: awardCategory, text: item.text, id: ++awardIndex });
}
const categories = [...new Set(awards.map(item => item.category))];
page('honours.html', 'Honours', `${heading('03', 'Recognition.<br>For a life of contribution.', 'National honours, scientific fellowships and recognition from communities around the world.')}<section class="award-feature wrap"><span class="award-symbol">${icon('award')}</span><div><span class="eyebrow">GOVERNMENT OF INDIA · 2016</span><h2>Padma Shri</h2><p>Recognising distinguished service in science and engineering.</p></div><strong>2016</strong></section><section class="awards-section wrap"><div class="section-top"><h2>The honours archive.</h2><span id="result-count" aria-live="polite">${awards.length} entries</span></div><div class="search-controls"><label>${icon('search')}<input id="award-search" type="search" placeholder="Search an award, institution or year" aria-label="Search honours"></label><select id="award-category" aria-label="Award category"><option value="all">All categories</option>${categories.map(category => `<option>${escape(category)}</option>`).join('')}</select></div><div class="award-list">${awards.map(item => `<article class="award-row" data-category="${escape(item.category)}"><span class="award-number">${String(item.id).padStart(2,'0')}</span><div><span class="mini">${escape(item.category)}</span><h3>${escape(item.text)}</h3></div>${icon('arrow-up-right')}</article>`).join('')}</div><p id="no-results" hidden>No honours match your search. Try another year or institution.</p><p class="source-note">Entries preserve the source archive, including fellowships and repeated recognitions across categories.</p></section>`);

const manifest = readFileSync(join(root, 'old/assets/image-links.txt'), 'utf8').split(/\r?\n/).filter(line => line.startsWith('https://'));
const archiveCategory = url => url.includes('/Books/') ? 'Books' : url.includes('Students') ? 'Students' : url.includes('family') ? 'Family' : url.includes('/ISRO/') ? 'ISRO' : url.includes('School') ? 'Education' : url.includes('Quotes') ? 'Quotes' : 'Life & events';
page('gallery.html', 'In focus', `${heading('04', 'A life, in focus.', 'The scientist, the missions and the public archive.')}<section class="wrap"><div class="photo-grid">${[['portrait.jpg','Dr. Mylswamy Annadurai','Portrait'],['moon.jpg','The Moon, photographed from Earth','Lunar destination'],['earth.jpg','Earth, photographed by Apollo 17','Our home planet']].map(([file,caption,label]) => `<button class="photo-tile" data-photo="assets/${file}" data-caption="${caption}" aria-label="Enlarge ${caption}"><img src="assets/${file}" alt="${caption}"><span><small>${label}</small>${caption}${icon('maximize-2')}</span></button>`).join('')}</div><p class="source-note">Portrait and space imagery: Wikimedia Commons. The Moon and Earth photographs illustrate the mission destinations, not photographs taken by Dr. Annadurai's missions. <a href="sources.html">Image credits</a>.</p></section><section class="wrap archive-section"><div class="section-top"><div><span class="eyebrow">FROM THE ORIGINAL COLLECTION</span><h2>The personal archive.</h2></div><select id="gallery-category" aria-label="Filter original archive"><option value="all">All subjects</option>${[...new Set(manifest.map(archiveCategory))].map(category => `<option>${category}</option>`).join('')}</select></div><p class="archive-note">Original photographs remain on the source website. Access may be restricted on some networks.</p><div class="archive-links">${manifest.map((url,index) => `<a href="${escape(url)}" class="archive-link" data-category="${archiveCategory(url)}" target="_blank" rel="noopener noreferrer"><span class="mini">${String(index + 1).padStart(2,'0')} / ${archiveCategory(url)}</span><span>${escape(decodeURIComponent(url.split('/').pop()).replace(/-min/gi,'').replace(/\.(jpg|jpeg|png)$/i,'').replaceAll('_',' '))}</span>${arrow}</a>`).join('')}</div></section><section class="wrap video-section"><span class="eyebrow">IN HIS OWN WORLD</span><h2>Stories &amp; conversations.</h2><div class="video-links">${link('https://www.youtube.com/watch?v=pLSUgxm4eK0', 'A brief life story', 'video-link')}${link('https://www.youtube.com/watch?v=K0hIB18WuM0', "Chat with India's Moon Man", 'video-link')}</div></section><dialog id="photo-dialog" aria-label="Photograph viewer"><button class="icon-button dialog-close" aria-label="Close photograph">${icon('x')}</button><img id="dialog-image" alt=""><p id="dialog-caption"></p></dialog>`);

const tamilWithoutTitle = tamil.replace(/^# .*\r?\n/, '').replace('## எதிர்வரும் நிகழ்வுகள்', '## நிகழ்வுகள் காப்பகம் · 2026');
page('tamil.html', 'நிலாத் தமிழர்', `${heading('05', 'முனைவர்<br>மயில்சாமி அண்ணாதுரை', 'நிலாத் தமிழர் · விண்வெளிப் பொறியாளர் · பத்மஸ்ரீ விருது பெற்றவர்')}<section class="tamil-intro wrap"><img src="assets/portrait.jpg" alt="முனைவர் மயில்சாமி அண்ணாதுரை"><p>கோதவாடியில் தொடங்கி விண்வெளி வரை சென்ற அறிவியல் பயணம்.</p></section><article class="prose wrap" lang="ta">${marked.parse(tamilWithoutTitle)}</article>`, 'ta');
page('sources.html', 'Sources & image credits', `${heading('06', 'The record<br>behind the story.', 'Source material, archive context and photographic credits.')}
<article class="prose wrap">
<h2>Biographical source</h2><p>This site is a redesigned presentation of the biography snapshot supplied from <a href="https://www.mylswamyannadurai.in/">mylswamyannadurai.in</a>, archived on 30 September 2026. The chronology and honours are drawn from that snapshot. Editorial summaries are not quotations.</p>
<p>Open-ended appointments and awards are reproduced as recorded, not independently certified. The Tamil events list is historical, not an upcoming calendar.</p>
<h2>Original records</h2><ul><li><a href="old/content/homeindex.md">English biography snapshot</a></li><li><a href="old/content/index-Tamil.md">Tamil biography snapshot</a></li><li><a href="old/assets/image-links.txt">Original photograph manifest</a></li></ul>
<h2>Photographs</h2><ul>
<li><a href="https://commons.wikimedia.org/wiki/File:Mylswamy_Annadurai.jpg">Mylswamy Annadurai portrait</a> · Ram 121 · Public domain, via Wikimedia Commons.</li>
<li><a href="https://commons.wikimedia.org/wiki/File:FullMoon2010.jpg">Full Moon (2010)</a> · Gregory H. Revera · <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Displayed with cropping and tonal overlays; these photographic adaptations are shared under the same licence.</li>
<li><a href="https://commons.wikimedia.org/wiki/File:The_Earth_seen_from_Apollo_17.jpg">The Blue Marble</a> · NASA / Apollo 17 crew · Public domain.</li></ul>
<p>The hero portrait is displayed in monochrome with a tonal overlay. Original source-gallery photographs are linked, not rehosted.</p>
<h2>Mission context</h2><p>Additional mission dates and context: <a href="https://www.isro.gov.in/Chandrayaan_1.html">ISRO: Chandrayaan-1</a>, <a href="https://www.isro.gov.in/MarsOrbiterMission.html">ISRO: Mars Orbiter Mission</a> and <a href="https://en.wikipedia.org/wiki/Mylswamy_Annadurai">Mylswamy Annadurai on Wikipedia</a>.</p>
<h2>Site assets</h2><p>Icons: Lucide, ISC licence. Typefaces: Google Fonts (Space Grotesk, DM Sans and Noto Sans Tamil), with local serif and sans-serif fallbacks. The site does not use analytics, trackers or contact forms.</p></article>`);
copyFileSync(join(root, 'node_modules/lucide/dist/umd/lucide.js'), join(root, 'assets/lucide.js'));
console.log(`Built 7 pages, ${awards.length} honours, ${timelineTokens.items.length} chronology entries and ${manifest.length} archive links.`);