import { readFileSync } from 'node:fs';
import { esc } from './visuals.mjs';

export const bibliography = JSON.parse(
  readFileSync(new URL('../data/books.json', import.meta.url), 'utf8'),
);

function cover(book, ta) {
  return `<a class="book-cover" href="${esc(book.coverSource)}" aria-label="${esc(ta ? `${book.titleTa} — அட்டைப்பட ஆதாரம்` : `${book.title} — cover source`)}"><img src="${esc(book.cover)}" width="${book.coverWidth}" height="${book.coverHeight}" alt="${esc(ta ? `${book.titleTa} நூலின் அட்டை` : `Cover of ${book.title}`)}" loading="lazy" decoding="async"></a>`;
}

export function renderBooks(language = 'en', preview = false, { collection = false } = {}) {
  const ta = language === 'ta';
  const id = collection ? 'archive-books' : preview ? 'books-preview' : 'books';
  const list = preview
    ? bibliography.books.filter((b) =>
        ['kaiyaruke-nila', 'siragai-virikkum-mangalyaan', 'vinnum-mannum'].includes(b.id),
      )
    : bibliography.books;
  const heading = ta
    ? 'அறிவியலை வாசிப்போம்.'
    : collection
      ? 'The bookshelf.'
      : 'Another way to explore.';
  return `<section class="books-section ${collection ? 'archive-book-shelf' : ta ? 'folio' : 'wrap'}${preview ? ' books-preview' : ''}" id="${id}"${collection ? ' data-collection="books"' : ''} aria-labelledby="${id}-title">
  <div class="books-heading"><div><span class="${ta ? 'kicker' : 'eyebrow'}">${ta ? 'எழுத்தில் ஒரு பயணம்' : 'THE SCIENTIST AS AN AUTHOR'}</span><h2 id="${id}-title">${heading}</h2></div>${preview ? '<a class="text-link" href="biography.html#books">Explore the bookshelf ↗</a>' : `<p>${ta ? 'வாழ்க்கை, விண்வெளி, அறிவியல் சிந்தனை — மயில்சாமி அண்ணாதுரையின் தமிழ் நூல்கள்.' : 'Memoir, space exploration and scientific thought, written for Tamil readers.'}</p>`}</div>
  <div class="books-grid">${list.map((book) => `<article class="book-card"${preview ? '' : ` id="book-${book.id}"`}>${cover(book, ta)}<div class="book-copy"><span class="book-theme">${esc(ta ? book.themeTa : book.theme)}</span><h3 lang="ta">${esc(book.titleTa)}</h3>${ta ? '' : `<p class="book-transliteration">${esc(book.title)}</p>`}${preview ? `<a class="book-link" href="biography.html#book-${book.id}">About this book ↗</a>` : `<p class="book-edition">${book.year ? `${ta ? 'பட்டியலிடப்பட்ட பதிப்பு' : 'Listed edition'} · ${book.year}` : ta ? 'வெளியீட்டு ஆண்டு உறுதியாகவில்லை' : 'Publication year unconfirmed'}${book.publisher ? `<br>${esc(ta ? book.publisherTa : book.publisher)}` : ''}</p>${book.collaborator ? `<p class="book-collaborator">${ta ? 'இணை ஆசிரியர்' : 'With'} ${esc(ta ? book.collaboratorTa : book.collaborator)}</p>` : ''}<p>${esc(ta ? book.summaryTa : book.summary)}</p><details class="book-details"><summary>${ta ? 'பதிப்பு விவரங்களும் ஆதாரங்களும்' : 'Edition details & sources'}</summary>${book.isbn ? `<p>ISBN ${book.isbn}</p>` : ''}<p>${esc(ta ? book.noteTa : book.note)}</p><ul>${book.sources.map((s) => `<li><a href="${esc(s.url)}">${esc(ta ? s.labelTa : s.label)} ↗</a></li>`).join('')}</ul><a href="${esc(bibliography.wikipedia)}">${ta ? 'விக்கிப்பீடியா நூல் பட்டியல்' : 'Wikipedia bibliography'} ↗</a></details>`}</div></article>`).join('')}</div>
  ${preview ? '' : `<div class="books-further"><h3>${ta ? 'மேலும் குறிப்பிடப்பட்டுள்ள நூல்கள்' : 'Further titles in the bibliography'}</h3><p>${ta ? 'பின்வரும் தலைப்புகள் விக்கிப்பீடியாவில் இடம்பெற்றுள்ளன. பதிப்பு விவரங்களும் அட்டைப்படங்களும் இன்னும் உறுதிப்படுத்தப்படவில்லை.' : 'These titles appear in Wikipedia; their editions and cover images still need confirmation.'}</p><div class="books-pending">${bibliography.pending.map((b) => `<article id="book-${b.id}"><h4 lang="ta">${esc(b.titleTa)}</h4>${ta ? '' : `<p class="book-transliteration">${esc(b.title)}</p>`}<p>${esc(ta ? b.noteTa : b.note)}</p></article>`).join('')}</div><p class="books-note">${ta ? '“வளரும் அறிவியல்”, “அறிவியல் களஞ்சியம்” ஆகியவற்றை விக்கிப்பீடியா தனித்தனியாகக் குறிப்பிடுகிறது. பதிப்பாளர் உறுதிப்படுத்தும் இணைந்த தலைப்பு இங்கு ஒரே நூலாகக் காட்டப்பட்டுள்ளது.' : 'Wikipedia lists “Valarum Ariviyal” and “Ariviyal Kalanjiyam” separately. The publisher confirms the combined title shown here; separate books have not been established.'} <a href="${esc(bibliography.wikipedia)}">${ta ? 'மூலப் பட்டியல்' : 'See the bibliography'} ↗</a></p><p class="books-note">${ta ? 'அட்டைப்படங்கள் நூல்களை அடையாளம் காண உதவுகின்றன; ஒவ்வொரு அட்டையும் அதன் ஆதாரத்துடன் இணைக்கப்பட்டுள்ளது. படங்களின் உரிமை தொடர்புடைய பதிப்பாளர்கள் மற்றும் படைப்பாளர்களிடமே உள்ளது.' : 'Cover thumbnails identify the books and link to their source listings. Artwork remains the property of its respective publishers and creators.'}</p></div>`}
  </section>`;
}

export function bookSources() {
  return `<h2 id="books-sources">Books and Wikipedia review</h2><p>The English and Tamil Wikipedia biographies were reviewed on 3 October 2026. Existing institutional date corrections take precedence over Wikipedia’s open-ended roles, unsupported ranking and patent claims. Factual summaries here are newly written, with catalogue references beside each book. Wikipedia’s eight labels are accounted for as five catalogue-supported books and two further titles; the two science labels map to one publisher-confirmed title. This is a reviewed bibliography, not a claim to an exhaustive list of published editions.</p><p><a href="${esc(bibliography.wikipedia)}">English Wikipedia · reviewed revision</a> · <a href="https://ta.wikipedia.org/w/index.php?title=%E0%AE%AE%E0%AE%AF%E0%AE%BF%E0%AE%B2%E0%AF%8D%E0%AE%9A%E0%AE%BE%E0%AE%AE%E0%AE%BF_%E0%AE%85%E0%AE%A3%E0%AF%8D%E0%AE%A3%E0%AE%BE%E0%AE%A4%E0%AF%81%E0%AE%B0%E0%AF%88&amp;oldid=4451912">Tamil Wikipedia · reviewed revision</a>. Wikipedia text is available under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>; its photographs and linked book covers have separate rights.</p><p>Dates identify catalogue editions unless stated otherwise. A 1 January retailer date is not asserted as a book-launch day. Coauthors are credited; ambiguous page counts and unconfirmed literary-award associations are explained on the book cards. <a href="biography.html#books">Browse the books</a>.</p><ul>${bibliography.books.map((b) => `<li><strong>${esc(b.title)}</strong>: ${b.sources.map((s) => `<a href="${esc(s.url)}">${esc(s.label)}</a>`).join(' · ')}. ${esc(b.coverCredit)} Cover reduced to a thumbnail, without rewriting or reconstructing its artwork.</li>`).join('')}</ul><h3>LinkedIn access and archive refresh</h3><p>The profile, honours and experience URLs returned HTTP 999 without usable content during this review. No new LinkedIn records or evidence pictures have been imported. The existing 79 honours and 37 career entries retain their source notes. On supported browsers, the home page prepares a local cache of this site’s published honours page and checks for changes every five minutes while visible. This refreshes the published archive; it does not query LinkedIn or independently verify new claims.</p>`;
}
