export function copyrightNotice(language = 'en') {
  return language === 'ta'
    ? '<div class="site-legal"><p>© 2026 முனைவர் மயில்சாமி அண்ணாதுரை — நிலாத் தமிழர். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.</p><p><a href="LICENSE">உரிமைக் குறிப்பு</a> · <a href="THIRD_PARTY_NOTICES.md">மூன்றாம் தரப்பினரின் உரிமைகள்</a> · <a href="#privacy">தனியுரிமை மற்றும் வெளிச்சேவைகள்</a></p></div>'
    : '<div class="site-legal"><p>© 2026 Dr. Mylswamy Annadurai — the Moon Man of India. All rights reserved.</p><p><a href="LICENSE">Proprietary notice</a> · <a href="THIRD_PARTY_NOTICES.md">Third-party rights</a> · <a href="sources.html#privacy">Privacy &amp; external services</a></p></div>';
}

export function privacyNotice(language = 'en') {
  return language === 'ta'
    ? `<div id="privacy"><h2>தனியுரிமை மற்றும் வெளிச்சேவைகள்</h2><p>இந்தத் தளத்தில் பகுப்பாய்வுக் கண்காணிப்போ தொடர்புப் படிவமோ இல்லை. ஆங்கில முகப்பும் விருதுகள் பக்கமும் இந்தத் தளத்தின் விருதுப் பதிவை உலாவியில் சேமித்து, பக்கம் தெரியும் போது ஐந்து நிமிடங்களுக்கு ஒருமுறை புதுப்பிப்பைச் சரிபார்க்கலாம். உலாவியில் இந்தத் தளத்தின் தரவை அழித்தால் அச்சேமிப்பும் நீங்கும். நூல் அட்டைகள் இந்தத் தளத்திலிருந்தே ஏற்றப்படுகின்றன. தளத்தை வழங்கும் சேவை தொழில்நுட்பப் பதிவுகளைச் சேகரிக்கலாம். பொது நாள்காட்டி Google-இலிருந்து பக்கம் திறக்கும்போது ஏற்றப்படுகிறது. ஆங்கிலப் பதிப்பின் எழுத்துருக்களும் Google-இலிருந்து பெறப்படுகின்றன.</p><p>YouTube காணொளிகள் நீங்கள் இயக்கக் கோரும்போது மட்டுமே இணைகின்றன. அப்போது உங்கள் இணைய முகவரி, உலாவி விவரங்கள் மற்றும் தள விவரங்கள் Google/YouTube-க்குச் செல்லலாம்; குக்கீகள் அல்லது பிற சேமிப்பு பயன்படுத்தப்படலாம். தனியுரிமை மேம்படுத்தப்பட்ட முறையும் முழுமையான பெயரறியாமைக்கு உத்தரவாதம் அல்ல. காணொளியை மூடுவது ஏற்கெனவே பகிர்ந்த தரவை நீக்காது.</p><p>இணைக்கப்பட்ட காணொளிகளுக்கு <a href="https://www.youtube.com/t/terms">YouTube பயன்பாட்டு விதிகள்</a> பொருந்தும். <a href="https://policies.google.com/privacy">Google தனியுரிமைக் கொள்கை</a> · <a href="https://support.google.com/youtube/answer/171780">YouTube காணொளி இணைப்பு வழிகாட்டி</a> · <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub தனியுரிமைக் கொள்கை</a>.</p><p>வெளியீட்டாளரின் காணொளிகள் அவர்களின் இயக்கியில் காட்டப்படுகின்றன; நகலெடுத்து இங்கு வழங்கப்படவில்லை. ஆதார இணைப்பு, உரிமையையோ நிறுவனத்தின் ஒப்புதலையோ குறிக்காது. மூன்றாம் தரப்புப் படங்களின் உரிமங்களும் படைப்பாளர் குறிப்புகளும் தக்கவைக்கப்பட்டுள்ளன.</p></div>`
    : `<div id="privacy"><h2>Privacy &amp; external services</h2><p>This site has no analytics, account system or contact form, and does not store visitor preferences. On supported browsers, the English home and honours pages cache this site’s published honours archive locally and check for updates every five minutes while visible. Clearing this site’s browser data removes that cache. Book cover thumbnails load from this site; following a source link opens the external catalogue. The hosting provider may retain technical access logs. Google Calendar loads public events when the overview or Tamil page opens; the English edition also requests fonts from Google.</p><p>YouTube players connect only when you choose “Watch here on YouTube”. Loading shares information such as your IP address, browser details and site origin with Google/YouTube, and may involve cookies or other storage. Privacy-enhanced mode limits personalization; it does not make playback anonymous. Closing a player removes it from this page but does not erase data already shared. Direct external links contact their destination when followed.</p><p>Embedded videos are subject to the <a href="https://www.youtube.com/t/terms">YouTube Terms of Service</a>. See the <a href="https://policies.google.com/privacy">Google Privacy Policy</a>, <a href="https://support.google.com/youtube/answer/171780">YouTube embedding guidance</a>, <a href="https://developers.google.com/youtube/terms/api-services-terms-of-service">YouTube API Services Terms</a>, <a href="https://developers.google.com/youtube/terms/developer-policies">developer policies</a> and <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub hosting privacy statement</a>.</p><h2 id="reuse-policy">Sources, embeds &amp; reuse</h2><p>Recordings remain with their publishers and use YouTube’s supported player. No video, audio, transcript or publisher thumbnail is copied into this site. If a publisher disables embedding or restricts playback, use the source link; the restriction is not bypassed. Interviews express the speakers’ views and are not independent verification of every biographical claim.</p><p>Official articles, registers and documents open at their original websites. A public URL, attribution or available embed does not by itself establish copyright ownership or permission for other reuse. Photographs retained here have individual source and licence records; those licences apply separately from this site’s proprietary notice. Links and institutional names do not imply endorsement.</p></div>`;
}
