import { bookSources } from './books.mjs';
import { reviewSources } from './review.mjs';
import { creditCards } from './visuals.mjs';
import { research } from './content.mjs';
import { privacyNotice } from './legal.mjs';
import { profileLinks, coverageSources } from './public-life.mjs';

export function renderSources() {
  return `<article class="prose wrap">
<h2 id="biographical-source">Biographical collection</h2><p>The biography, appointments and honours draw on the supplied biographical collection dated 30 September 2026. Its text records are maintained with this project. They are reconstructed from retrieved text, rather than original server HTML. Editorial summaries are not quotations. An open-ended appointment records no end date; it does not independently establish that the appointment is current.</p>
<h2 id="editorial-notes">Reading the record carefully</h2><p>Official references were checked on 3 October 2026 and linked beside chronology entries, selected honours and page topics. A mission page supports mission facts, not an individual’s tenure. Every career and honours entry now states its verification status; collection-only dates are not presented as independently confirmed. The official URSC biography independently supports several education, career and award claims.</p><ul>
<li><strong>H.K. Firodia Award:</strong> the <a href="https://www.ursc.gov.in/directors/annadurai.jsp">official URSC biography</a> gives 2007; the supplied honours collection gives 2009. The <a href="https://hkfirodiaawards.org/awards-by-year.php">award provider’s year-by-year register</a> confirms 2009, which this edition adopts.</li>
<li><strong>Education:</strong> the profile uses “Government College of Engineering”; the chronology names Government College of Technology, Coimbatore. This edition follows the chronology. The PhD year is not recorded; honorary doctorates are listed separately.</li>
<li><strong>INSAT-3B:</strong> the English chronology names INSAT-3B (2000–2010); the Tamil record uses the designation INSAT-3P. Both editions now use INSAT-3B; the personal tenure still relies on the collection.</li>
<li><strong>Edutec4 Space:</strong> the English title is Patron; the Tamil text describes a senior advisor.</li>
<li><strong>Dhaksha Unmanned Systems:</strong> English dates are 2023–2026; the Tamil record gives 2024 onwards. Neither discrepancy has been independently reconciled.</li>
<li><strong>Honours:</strong> BHASKARA (2016) and SIES National Eminence (2009) are separate honours. The 2024 Weekend Leader / Ethiraj College award appears in two categories: 79 entries represent 78 distinct recognitions.</li>
<li><strong>Unknown dates:</strong> no year is inferred from “AISYWC-18”, “76th Indian Science Congress” or an anniversary. The unconfirmed UCLA range is retained internally but excluded from the displayed year filters.</li>
<li><strong>Different award records:</strong> the Tamil collection has fewer entries. It dates the Outstanding Personality Award to 24 May 2024; the English inventory gives 25 May. Both editions show May 2024 and flag the conflicting days.</li>
<li><strong>Books, photographs and family:</strong> 40 image filenames survive in the inventory, but the photographs are unavailable here. Filenames do not establish book titles, identities or dates. A separate researched bookshelf now supplies catalogue-backed titles and cover thumbnails. The family collection records a “Speech/address by Ayya’s father”; no recording URL is available.</li></ul>
<h2 id="internet-research">Further reading, talks and interviews</h2><p>Eight additional recordings were selected from original publisher uploads on 2 October 2026, supplementing two existing links. This English edition presents eight recordings; the Tamil edition presents the two Tamil interviews. Selection considered relevance, publisher provenance and range of perspectives. View counts are dated snapshots, not audience ratings.</p><p>YouTube metadata supplied titles, publishers, upload timestamps and durations. All ten recordings were rechecked on 3 October 2026. Publication timestamps are displayed in Indian Standard Time; they are not assumed to be the dates of the recorded events. Summaries follow publisher titles and descriptions; the recordings have not been transcribed or reviewed in full. Player metadata reported availability, but complete playback was not verified. Source links appear on the <a href="gallery.html#watch">recording cards</a>.</p><ul>${research.sources.map((item) => `<li><a href="${item.url}">${item.title}</a> · ${item.publisher}. ${item.finding} ${item.scope}</li>`).join('')}</ul>
<p><strong>NDRF discrepancy:</strong> the <a href="https://www.ndrf.res.in/chairmen.html">institutional register</a> gives 18 February 2019–7 March 2022, while the biographical collection gives 2019–2023 and reverses “Design” and “Research” in the organization name. Both editions now use the institutional register’s dates and corrected organization name.</p><p><strong>Excluded claims:</strong> one podcast description incorrectly calls Annadurai a former ISRO chairman. This biography uses his satellite-centre directorship. Patent US7185858B2 lists other inventors and is not attributed to him. A republication of the banana-fibre report is not treated as a second independent confirmation.</p>
${reviewSources()}${coverageSources()}${bookSources()}<h2 id="image-credits">Photographs &amp; the people behind them</h2><p>Explore the source, photographer and reuse licence for each addition. Government photographs are reused under the Government Open Data License – India; public-domain images are labelled separately.</p>${creditCards()}<ul><li><a href="https://commons.wikimedia.org/wiki/File:Mylswamy_Annadurai.jpg">Mylswamy Annadurai portrait</a> · Ram 121 · Public domain, via Wikimedia Commons.</li><li><a href="https://commons.wikimedia.org/wiki/File:FullMoon2010.jpg">Full Moon (2010)</a> · Gregory H. Revera · <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Resized and displayed with cropping and tonal overlays; these photographic adaptations are shared under the same licence.</li><li><a href="https://commons.wikimedia.org/wiki/File:The_Earth_seen_from_Apollo_17.jpg">The Blue Marble</a> · NASA / Apollo 17 crew · Public domain.</li></ul><p>These three existing images accompany seven newly sourced archival and mission images, all delivered locally as optimized WebP files. The existing full Moon and Earth images illustrate mission destinations. The newly added scientific maps are actual Moon Mineralogy Mapper data from Chandrayaan-1. The remaining 40 image records have incomplete context and unestablished reuse rights; no unavailable photographs are embedded or linked.</p>
<h2>Mission references</h2><p>Mission context draws on <a href="https://www.isro.gov.in/Chandrayaan_1.html">ISRO: Chandrayaan-1</a>, <a href="https://science.nasa.gov/mission/chandrayaan-1/">NASA: Chandrayaan-1</a> and <a href="https://www.isro.gov.in/MarsOrbiterMissionSpacecraft.html">ISRO: Mars Orbiter Mission</a>. Roles and tenures follow the biographical collection.</p>
<h2>Follow Dr. Annadurai</h2>${profileLinks()}
<h2>Site assets</h2><p>Icons: Lucide, ISC licence. English typefaces: Space Grotesk and DM Sans, with system fallbacks. Video players connect to YouTube only when requested. This site has no analytics or contact form.</p>${privacyNotice()}</article>`;
}
