import { bookSources } from './books.mjs';
import { reviewSources } from './review.mjs';
import { creditCards } from './visuals.mjs';
import { research } from './content.mjs';
import { privacyNotice } from './legal.mjs';
import { profileLinks, coverageSources } from './public-life.mjs';

export function renderSources() {
  return `<article class="prose wrap">
<h2 id="biographical-source">Biographical collection</h2><p>The biography, appointments and honours draw on Dr. Annadurai’s biographical collection dated 30 September 2026, alongside the institutional and press references linked throughout this site.</p>
<h2 id="editorial-notes">About the records</h2><p>Dates and descriptions follow the cited institutional records. Editorial summaries are written for this biography. The original research and source texts are preserved with the project.</p><ul>
<li><strong>H.K. Firodia Award:</strong> this edition follows the <a href="https://hkfirodiaawards.org/awards-by-year.php">award provider’s register</a>, which dates the honour to 2009.</li>
<li><strong>Honours:</strong> BHASKARA (2016) and SIES National Eminence (2009) are separate honours. The 2024 Weekend Leader / Ethiraj College award appears in two categories: 79 entries represent 78 distinct recognitions.</li>
<li><strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/dr-mylswamy-annadurai-05641a1/details/honors/">Dr. Annadurai’s honours page</a> accompanies the institutional and press references.</li>
<li><strong>Education:</strong> honorary doctorates are listed separately from academic qualifications.</li></ul>
<h2 id="internet-research">Further reading, talks and interviews</h2><p>Eight additional recordings were selected from original publisher uploads on 2 October 2026, supplementing two existing links. This English edition presents eight recordings; the Tamil edition presents the two Tamil interviews. Selection considered relevance, publisher provenance and range of perspectives. View counts are dated snapshots, not audience ratings.</p><p>Recording cards show publisher titles, upload dates and durations. Publication timestamps use Indian Standard Time. Source links appear on the <a href="gallery.html#watch">recording cards</a>.</p><ul>${research.sources.map((item) => `<li><a href="${item.url}">${item.title}</a> · ${item.publisher}. ${item.finding} ${item.scope}</li>`).join('')}</ul>
<p><strong>NDRF discrepancy:</strong> the <a href="https://www.ndrf.res.in/chairmen.html">institutional register</a> gives 18 February 2019–7 March 2022, while the biographical collection gives 2019–2023 and reverses “Design” and “Research” in the organization name. Both editions now use the institutional register’s dates and corrected organization name.</p>
${reviewSources()}${coverageSources()}${bookSources()}<h2 id="image-credits">Photographs &amp; the people behind them</h2><p>Explore the source, photographer and reuse licence for each addition. Government photographs are reused under the Government Open Data License – India; public-domain images are labelled separately.</p>${creditCards()}<ul><li><a href="https://commons.wikimedia.org/wiki/File:Mylswamy_Annadurai.jpg">Mylswamy Annadurai portrait</a> · Ram 121 · Public domain, via Wikimedia Commons.</li><li><a href="https://commons.wikimedia.org/wiki/File:FullMoon2010.jpg">Full Moon (2010)</a> · Gregory H. Revera · <a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>. Resized and displayed with cropping and tonal overlays; these photographic adaptations are shared under the same licence.</li><li><a href="https://commons.wikimedia.org/wiki/File:The_Earth_seen_from_Apollo_17.jpg">The Blue Marble</a> · NASA / Apollo 17 crew · Public domain.</li></ul><p>Portraits, the vintage collage and archival mission images are delivered locally as optimized WebP files. The Moon and Earth photographs illustrate mission destinations; the scientific maps show Moon Mineralogy Mapper data from Chandrayaan-1.</p>
<h2>Mission references</h2><p>Mission context draws on <a href="https://www.isro.gov.in/Chandrayaan_1.html">ISRO: Chandrayaan-1</a>, <a href="https://science.nasa.gov/mission/chandrayaan-1/">NASA: Chandrayaan-1</a> and <a href="https://www.isro.gov.in/MarsOrbiterMissionSpacecraft.html">ISRO: Mars Orbiter Mission</a>. Roles and tenures follow the biographical collection.</p>
<h2>Follow Dr. Annadurai</h2>${profileLinks()}
<h2>Site assets</h2><p>Icons: Lucide, ISC licence. English typefaces: Space Grotesk and DM Sans, with system fallbacks. Video players connect to YouTube only when requested. This site has no analytics or contact form.</p>${privacyNotice()}</article>`;
}
